const blogData = [
    {
      id: 1,
      title: "Top 10 Tips for First-Time Home Buyers",
      image: "blog1.jpg",
      shortDesc: "A simple guide to help new buyers understand budgets, loans, and inspections.",
      date: "2025-01-08",
      comments: 14,
      author: "Rohan Desai",
    },
    {
      id: 2,
      title: "Why Investing in Real Estate Still Makes Sense",
      image: "blog2.jpg",
      shortDesc: "Explore long-term benefits, rental income, and capital growth opportunities.",
      date: "2025-01-10",
      comments: 9,
      author: "Ananya Kapoor",
    },
    {
      id: 3,
      title: "How to Identify a Good Neighborhood Before Buying",
      image: "blog3.jpg",
      shortDesc: "Location matters—here’s what to check before finalizing your dream home.",
      date: "2025-01-12",
      comments: 7,
      author: "Arjun Mehta",
    },
    {
      id: 4,
      title: "Modern Interior Trends for 2025 Homes",
      image: "blog4.jpg",
      shortDesc: "Discover trending colors, layouts, and furniture ideas for modern living.",
      date: "2025-01-15",
      comments: 18,
      author: "Sara Thomas",
    },
    {
      id: 5,
      title: "Renting vs Buying: Which Is Better in 2025?",
      image: "blog5.jpg",
      shortDesc: "A balanced look at pros, cons, and financial considerations.",
      date: "2025-01-18",
      comments: 11,
      author: "Vikram Shah",
    },
    {
      id: 6,
      title: "How to Increase Your Property Value Easily",
      image: "blog6.jpg",
      shortDesc: "Simple upgrades that boost your home’s resale price without overspending.",
      date: "2025-01-22",
      comments: 22,
      author: "Nisha Patel",
    },
    {
      id: 7,
      title: "Understanding Home Loans in India",
      image: "blog7.jpg",
      shortDesc: "From interest rates to eligibility—everything explained in simple words.",
      date: "2025-01-24",
      comments: 8,
      author: "Karan Joshi",
    },
    {
      id: 8,
      title: "Things to Check Before Signing a Rent Agreement",
      image: "blog8.jpg",
      shortDesc: "Avoid legal issues by checking these important clauses and conditions.",
      date: "2025-01-26",
      comments: 16,
      author: "Meera Acharya",
    },
    {
      id: 9,
      title: "Best Property Investment Locations for 2025",
      image: "blog9.jpg",
      shortDesc: "Upcoming areas with strong growth, good connectivity, and better returns.",
      date: "2025-01-28",
      comments: 10,
      author: "Yash Verma",
    },
    {
      id: 10,
      title: "How to Stage Your Home for Faster Selling",
      image: "blog10.jpg",
      shortDesc: "Proven styling tips to attract more buyers and secure a better price.",
      date: "2025-01-30",
      comments: 6,
      author: "Pooja Nair",
    },
    {
      id: 11,
      title: "Understanding Property Taxes in India",
      image: "blog11.jpg",
      shortDesc: "A quick overview of how property tax works and what homeowners must know.",
      date: "2025-02-01",
      comments: 20,
      author: "Siddharth Iyer",
    },
    {
      id: 12,
      title: "Checklist Before Booking an Under-Construction Property",
      image: "blog12.jpg",
      shortDesc: "Important approvals, builder reputation, and RERA details you must check.",
      date: "2025-02-03",
      comments: 13,
      author: "Ritika Khanna",
    },
  ];
  
  export default blogData;
  